# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Badge.destroy_all

Badge.create(name: "aladdin", url: "aladdin.png")
Badge.create(name: "alice", url: "alice.png")
Badge.create(name: "anna", url: "anna.png")
Badge.create(name: "ariel", url: "ariel.png")
Badge.create(name: "attaant", url: "attaant.png")
Badge.create(name: "aurora", url: "aurora.png")
Badge.create(name: "baloo", url: "baloo.png")
Badge.create(name: "beast", url: "beast.png")
Badge.create(name: "belle", url: "belle.png")
Badge.create(name: "bobafett", url: "bobafett.png")
Badge.create(name: "bolt", url: "bolt.png")
Badge.create(name: "boo", url: "boo.png")
Badge.create(name: "brerfox", url: "brerfox.png")
Badge.create(name: "brerrabbit", url: "brerrabbit.png")
Badge.create(name: "buzz", url: "buzz.png")
Badge.create(name: "captainhook", url: "captainhook.png")
Badge.create(name: "chewy", url: "chewy.png")
Badge.create(name: "chipndale", url: "chipndale.png")
Badge.create(name: "cinderella", url: "cinderella.png")
Badge.create(name: "cruella", url: "cruella.png")
Badge.create(name: "daisy", url: "daisy.png")
Badge.create(name: "darthvader", url: "darthvader.png")
Badge.create(name: "donald", url: "donald.png")
Badge.create(name: "eeyore", url: "eeyore.png")
Badge.create(name: "elastigirl", url: "elastigirl.png")
Badge.create(name: "elsa", url: "elsa.png")
Badge.create(name: "fairygodmother", url: "fairygodmother.png")
Badge.create(name: "fawn", url: "fawn.png")
Badge.create(name: "flick", url: "flick.png")
Badge.create(name: "frozone", url: "frozone.png")
Badge.create(name: "gaston", url: "gaston.png")
Badge.create(name: "genie", url: "genie.png")
Badge.create(name: "gepetto", url: "gepetto.png")
Badge.create(name: "goofy", url: "goofy.png")
Badge.create(name: "greenarmymen", url: "greenarmymen.png")
Badge.create(name: "handyman", url: "handyman.png")
Badge.create(name: "iridessa", url: "iridessa.png")
Badge.create(name: "jafar", url: "jafar.png")
Badge.create(name: "jesse", url: "jesse.png")
Badge.create(name: "jiminy", url: "jiminy.png")
Badge.create(name: "launchpad", url: "launchpad.png")
Badge.create(name: "madhatter", url: "madhatter.png")
Badge.create(name: "maleficent", url: "maleficent.png")
Badge.create(name: "marypoppins", url: "marypoppins.png")
Badge.create(name: "max", url: "max.png")
Badge.create(name: "meg", url: "meg.png")
Badge.create(name: "merida", url: "merida.png")
Badge.create(name: "mickey", url: "mickey.png")
Badge.create(name: "minnie", url: "minnie.png")
Badge.create(name: "mrincredible", url: "mrincredible.png")
Badge.create(name: "mrsmee", url: "mrsmee.png")
Badge.create(name: "mulan", url: "mulan.png")
Badge.create(name: "peterpan", url: "peterpan.png")
Badge.create(name: "piglet", url: "piglet.png")
Badge.create(name: "pinocchio", url: "pinocchio.png")
Badge.create(name: "pluto", url: "pluto.png")
Badge.create(name: "pooh", url: "pooh.png")
Badge.create(name: "princeeric", url: "princeeric.png")
Badge.create(name: "queenofhearts", url: "queenofhearts.png")
Badge.create(name: "r2d2", url: "r2d2.png")
Badge.create(name: "rabbit", url: "rabbit.png")
Badge.create(name: "rafiki", url: "rafiki.png")
Badge.create(name: "rapunzel", url: "rapunzel.png")
Badge.create(name: "rosetta", url: "rosetta.png")
Badge.create(name: "santa", url: "santa.png")
Badge.create(name: "scrooge", url: "scrooge.png")
Badge.create(name: "sevendwarfs", url: "sevendwarfs.png")
Badge.create(name: "silvermist", url: "silvermist.png")
Badge.create(name: "snowwhite", url: "snowwhite.png")
Badge.create(name: "snowwhitequeen ", url: "snowwhitequeen.png")
Badge.create(name: "stormtrooper", url: "stormtrooper.png")
Badge.create(name: "sully", url: "sully.png")
Badge.create(name: "tigger", url: "tigger.png")
Badge.create(name: "timon", url: "timon.png")
Badge.create(name: "tink", url: "tink.png")
Badge.create(name: "whiterabbit", url: "whiterabbit.png")
Badge.create(name: "woody", url: "woody.png")
